server:
  port: 8081

spring:
  application:
    name: display

hystrix:
  command:
    productInfo: #commandKey로 지정됨. 'default'지정 시 global setting
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 # default 1000ms
      circuitBreaker:
        requestVolumeThreshold: 1 #default 20
        errorThresholdPercentage: 50 #default 50
    FeignProductRemoteService#getProductInfo(String):
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
product:
  ribbon:
    #    listOfServers: localhost:8082, localhost:7777 #eureka를 통해 서버리스트를 가져오게 됨
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka #default address